default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  username: signonotron2
  password: signonotron2
  pool: 5

development:
  <<: *default
  database: signonotron2_development
  url: <%= ENV["DATABASE_URL"] %>

test: &test
  <<: *default
  database: signonotron2_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  database: halberd_production
  username: halberd
  password:
  url: <%= ENV["DATABASE_URL"] %>
